baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = 'ananke'

disablePathToLower = true
title = "rmauro.dev {blog}"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
